- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.9
  hooks:
    - id: cmake-format
    - id: cmake-lint
- repo: local
  hooks:
    - id: clang-format
      name: Clang Format
      description: Format C++ with clang-format.
      entry: ./scripts/clang_format.py
      language: python
      files: '.*\.cpp$'
    - id: clang-tidy
      name: Clang Tidy
      description: Lint C++ with clang-tidy.
      entry: ./scripts/clang_tidy.py
      language: python
      files: '.*\.cpp'
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 5c459f3f27ae62fefef60fe5771e51baa02e7a83
  hooks:
    - id: autopep8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 323f177eb169987f7034a75d0a195e4448eec0ba
  hooks:
    - id: mypy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
